import html
import os
import subprocess
import tempfile
import time
import tomllib
import traceback
import webbrowser
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class CheckDefinition:
    id: str
    group: str
    label: str
    setup: str
    command: str
    expected: str
    action: Callable[[], str]


@dataclass(frozen=True)
class CheckResult:
    definition: CheckDefinition
    status: str
    observed: str
    detail: str = ""


def run_command(command: list[str]) -> str:
    result = subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=300,
    )
    if result.returncode:
        raise RuntimeError(f"Command failed ({' '.join(command)}):\n{result.stdout}")
    return result.stdout


def project_name() -> str:
    pyproject = tomllib.loads((PROJECT_ROOT / "pyproject.toml").read_text())
    return str(pyproject["tool"]["poetry"]["name"])


def check_rendered_project() -> str:
    unresolved_files = []
    markers = ("{" + "{", "{" + "%")
    excluded_parts = {
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".venv",
        "acceptance",
    }
    for path in PROJECT_ROOT.rglob("*"):
        if not path.is_file():
            continue
        relative_path = path.relative_to(PROJECT_ROOT)
        if excluded_parts.intersection(relative_path.parts):
            continue
        try:
            content = path.read_text()
        except UnicodeDecodeError:
            continue
        if any(marker in content for marker in markers):
            unresolved_files.append(relative_path.as_posix())
    if unresolved_files:
        raise RuntimeError(f"Unresolved template markers: {unresolved_files}")
    return f"{project_name()} contains no unresolved template markers."


def check_git_hooks() -> str:
    if not (PROJECT_ROOT / ".git").is_dir():
        raise RuntimeError("Git is not initialized.")
    for hook in ("pre-commit", "pre-push"):
        hook_path = PROJECT_ROOT / ".git/hooks" / hook
        if not hook_path.is_file() or not os.access(hook_path, os.X_OK):
            raise RuntimeError(f"The {hook} hook is not installed and executable.")
    return "Git is initialized and both hooks are executable."


def check_poetry_lock() -> str:
    run_command(["poetry", "check", "--lock"])
    return "Poetry metadata and the lock file agree."


def check_static_quality() -> str:
    run_command(["make", "check"])
    return "Ruff formatting, Ruff linting, and strict MyPy passed."


def check_application() -> str:
    run_command(["make", "test"])
    return "The FastAPI health integration test passed."


def check_compose() -> str:
    run_command(["docker", "compose", "config", "--quiet"])
    return "Docker Compose resolved without configuration errors."


CHECKS = [
    CheckDefinition(
        id="GEN-01",
        group="Generation",
        label="Project is fully rendered",
        setup="A project generated by Copier.",
        command="Scan generated text files for unresolved template markers",
        expected="No unresolved template syntax remains.",
        action=check_rendered_project,
    ),
    CheckDefinition(
        id="SETUP-01",
        group="Developer setup",
        label="Git repository and hooks are ready",
        setup="make setup has initialized the project.",
        command="Inspect .git/hooks/pre-commit and .git/hooks/pre-push",
        expected="Git exists and both hooks are executable.",
        action=check_git_hooks,
    ),
    CheckDefinition(
        id="QUAL-03",
        group="Quality",
        label="Poetry lock is consistent",
        setup="Poetry dependencies are installed.",
        command="poetry check --lock",
        expected="Project metadata and poetry.lock agree.",
        action=check_poetry_lock,
    ),
    CheckDefinition(
        id="QUAL-01",
        group="Quality",
        label="Static checks pass",
        setup="The generated source and test tree.",
        command="make check",
        expected="Ruff formatting, Ruff linting, and strict MyPy pass.",
        action=check_static_quality,
    ),
    CheckDefinition(
        id="QUAL-02",
        group="Application",
        label="FastAPI integration test passes",
        setup="The generated FastAPI application.",
        command="make test",
        expected="The health endpoint integration test passes.",
        action=check_application,
    ),
    CheckDefinition(
        id="CTR-01",
        group="Containers",
        label="Docker Compose configuration resolves",
        setup="Docker Desktop and the generated Compose file.",
        command="docker compose config --quiet",
        expected="Compose resolves without errors.",
        action=check_compose,
    ),
]


REPORT_STYLES = """
:root {
  color-scheme: dark;
  --ink: #edede7;
  --muted: #92928d;
  --line: #30302d;
  --accent: #d8ff36;
  --panel: #131312;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: #080808;
  color: var(--ink);
  font: 400 14px/1.6 ui-monospace, 'SFMono-Regular', Consolas, monospace;
}
main { width: min(820px, calc(100% - 32px)); margin: 0 auto; padding: 56px 0; }
h1 { margin: 0 0 6px; font-size: clamp(1.7rem, 5vw, 2.7rem); font-weight: 300; }
p { margin: 0; color: var(--muted); }
.summary { margin: 30px 0 18px; padding: 12px 0; border-block: 1px solid var(--line); }
.summary strong { color: var(--accent); font-weight: 400; }
.group { margin-top: 24px; }
.group-title { display: flex; justify-content: space-between; margin-bottom: 8px; }
.group-title h2 { margin: 0; font-size: .82rem; font-weight: 400; text-transform: uppercase; }
.group-title span { color: var(--muted); font-size: .68rem; }
.case {
  margin: 7px 0;
  border: 1px solid var(--line);
  border-radius: 4px;
  background: var(--panel);
}
summary {
  display: grid;
  grid-template-columns: 72px minmax(0, 1fr) auto 18px;
  align-items: center;
  gap: 20px;
  padding: 13px 15px;
  cursor: pointer;
}
summary strong { color: #8bd17c; font-size: .72rem; font-weight: 400; }
.case-id { color: var(--accent); font-size: .7rem; }
.failed summary strong { color: #ff806d; }
.chevron { color: var(--muted); font-size: 1.35rem; line-height: 1; }
details[open] .chevron { transform: rotate(90deg); color: var(--accent); }
.detail { border-top: 1px solid var(--line); }
.detail section {
  display: grid;
  grid-template-columns: 110px minmax(0, 1fr);
  gap: 16px;
  padding: 12px 15px;
  border-bottom: 1px solid #242421;
}
.detail section:last-child { border-bottom: 0; }
.detail .result { box-shadow: inset 2px 0 0 var(--accent); }
h3 { margin: 2px 0 0; color: var(--muted); font-size: .68rem; font-weight: 400; }
.detail p { color: var(--ink); }
pre {
  margin: 0;
  padding: 9px 11px;
  border: 1px solid var(--line);
  border-radius: 3px;
  background: #181817;
  white-space: pre-wrap;
  color: var(--ink);
  overflow: auto;
}
@media (max-width: 620px) {
  .detail section { grid-template-columns: 1fr; gap: 5px; }
}
"""


def print_progress(completed: int, result: CheckResult, elapsed: float) -> None:
    filled = round(12 * completed / len(CHECKS))
    bar = "█" * filled + "░" * (12 - filled)
    print(
        f"[{completed}/{len(CHECKS)}] {bar} {result.status:<6} "
        f"{result.definition.id} {result.definition.label} ({elapsed:.1f}s)"
    )


def run_checks() -> list[CheckResult]:
    results = []
    print(f"\nChecking {project_name()}…")
    for completed, check in enumerate(CHECKS, start=1):
        print(f"\nRunning {check.id} · {check.label}")
        print(f"  {check.command}")
        started_at = time.monotonic()
        try:
            result = CheckResult(check, "passed", check.action())
        except Exception:
            result = CheckResult(
                check,
                "failed",
                "Failed. Open the report for diagnostics.",
                traceback.format_exc(),
            )
        print_progress(completed, result, time.monotonic() - started_at)
        results.append(result)
    return results


def render_case(result: CheckResult) -> str:
    check = result.definition
    diagnostics = (
        f"<section><h3>Diagnostics</h3><pre>{html.escape(result.detail)}</pre></section>"
        if result.detail
        else ""
    )
    return f"""
      <details class="case {result.status}">
        <summary><span class="case-id">{check.id}</span><span>{html.escape(check.label)}</span>
          <strong>{result.status}</strong><span class="chevron">›</span></summary>
        <div class="detail">
          <section><h3>Setup</h3><p>{html.escape(check.setup)}</p></section>
          <section><h3>Command</h3><pre>{html.escape(check.command)}</pre></section>
          <section><h3>Expected</h3><p>{html.escape(check.expected)}</p></section>
          <section class="result"><h3>Result</h3><p>{html.escape(result.observed)}</p></section>
          {diagnostics}
        </div>
      </details>
    """


def render_groups(results: list[CheckResult]) -> str:
    groups = []
    for group in dict.fromkeys(result.definition.group for result in results):
        group_results = [result for result in results if result.definition.group == group]
        cases = "".join(render_case(result) for result in group_results)
        groups.append(
            f'<section class="group"><div class="group-title"><h2>{group}</h2>'
            f"<span>{len(group_results)} checks</span></div>{cases}</section>"
        )
    return "".join(groups)


def write_report(results: list[CheckResult]) -> Path:
    default_path = Path(tempfile.gettempdir()) / "fastapi-generated-repository-validation.html"
    report_path = Path(os.environ.get("PROJECT_REPORT_PATH", default_path))
    passed = sum(result.status == "passed" for result in results)
    blockers = len(results) - passed
    report_title = f"FastAPI Starter Check: {html.escape(project_name())}"
    report_path.write_text(
        f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{report_title}</title><style>{REPORT_STYLES}</style></head>
<body><main><h1>{report_title}</h1>
<p>A fresh FastAPI repository that installs, tests, and runs.</p>
<div class="summary"><strong>{passed}/{len(results)} passed</strong> · {blockers} blockers</div>
{render_groups(results)}</main></body></html>"""
    )
    return report_path


def open_report(report_path: Path) -> None:
    if os.environ.get("CI"):
        return
    try:
        if not webbrowser.open(report_path.as_uri()):
            print("The browser did not open; use the report link above.")
    except webbrowser.Error:
        print("The browser did not open; use the report link above.")


def main() -> int:
    results = run_checks()
    report_path = write_report(results)
    passed = sum(result.status == "passed" for result in results)
    print()
    if passed == len(results):
        print(f"All set — {project_name()} is ready.")
    else:
        print(f"Setup needs attention — {len(results) - passed} checks failed.")
    print(f"{passed}/{len(results)} checks passed")
    print(f"Visual report: {report_path.as_uri()}")
    open_report(report_path)
    return 0 if passed == len(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
